# --- !Ups

create table note (
  id bigint generated by default as identity(start with 1) not null primary key,
  name varchar not null
);

create table note_item (
    id bigint generated by default as identity (start with 1) not null primary key,
    content varchar not null ,
    is_done boolean not null ,
    note_id bigint,
    CONSTRAINT note_item_f_key FOREIGN key (note_id) REFERENCES note(id) match simple
    on update No action on delete cascade
)
# --- !Downs

drop table note_item if exists;
drop table note if exists;
